### PR TITLE
Documenting use of sleep to defer actions briefly.

### PR DESCRIPTION
**Pull request by dsalt**
This is intended to show resolution of conflict between `devilspie2` and other programs re. actions on windows. See #11 for more info.

This pull request exists for comments & discussion, if any is needed.

### CODE REVIEW

**Comment by davidhedlund** [comment]
Should this be mentioned in the comments (minus "[1]" and the link that I added for you):

```
The preferred method for maximizing Emacs involves using an early-init.el file, which allows for quicker maximization compared to configuring it in init.el.[1]

However, many Emacs users prefer to keep all their configuration in init.el. In such cases, devilspie2 can be a useful alternative for achieving quick maximization without modifying the Emacs startup process.
```

1: See "early-init.el" at https://www.emacswiki.org/emacs/FullScreen for reference.

**Comment by davidhedlund** [comment]
I updated my comment. devilspie2 will cause a slight delay compared to early-init.el. devilspie2 is still useful for emacs beginners.

**Comment by dsalt** [comment]
That's more detail than is needed here, I think, but I may still use it (without a comma before “or using”).

Also, I'm considering this:

> If you prefer, you can have Emacs maximise its window (as in this example) via one of its configuration files - early-init.el, which is normally faster, or init.el.

(Incidentally, I can get away with `millisleep(10)` / `os.execute("sleep 0.01")`.)

**Comment by davidhedlund** [comment]
> That's more detail than is needed here, I think, but I may still use it (without a comma before “or using”).
> 
> Also, I'm considering this:
> 
> > If you prefer, you can have Emacs maximise its window (as in this example) via one of its configuration files - early-init.el, which is normally faster, or init.el.

I like it, it's short and concise.

> (Incidentally, I can get away with `millisleep(10)` / `os.execute("sleep 0.01")`.)

The current time is set to 0.1 in the PR. init.el has a default delay of 0.3 second. This will cause a total delay of 0.4 second. As I mentioned earlier, my computer solves it at `os.execute("sleep 0.02")` to avoid adding. Should we lower it to 0.05? That is 0.05 s less, or 1/4th of the total delay (when early.init is used). Maybe I'm exaggerating, 0.1 is fine.

**Comment by dsalt** [comment]
Hah, looks like edit and reply crossed…

Use mine, then? Either way, I'll add notes about changing the sleep time and the LISP statement will be included.

**Comment by davidhedlund** [comment]
> in this
>  -- case, 'millisleep(10)' (0.01s) seems fine for most modern PCs.

I think you mean:

> in this
>  -- case, 'millisleep(100)' (0.1s) seems fine for most modern PCs.

Also your PR didn't work for me, it didn't maximize emacs at all:

```
win_class = get_class_instance_name()

debug_print("Window class: " .. win_class)

if win_class == "emacs" or win_class == "Emacs" then
  millisleep(100)
  maximise()
end
```

**Comment by davidhedlund** [comment]
Oh, millisleep is not distributed in any release yet. meanwhile, why not use `os.execute` like you originally came up with?:

```
if get_class_instance_name() == "emacs" then
  os.execute("sleep 0.1")
  maximize()
end
```

**Comment by dsalt** [comment]
I specifically meant 0.01s. (Yes, I tested it.) Anyway, reworded…

**Comment by davidhedlund** [comment]
I found a typo in your PR, maximize it typed maximise:
> maximi**s**e()

**Comment by dsalt** [comment]
No error. See 14aefcdbf9f94074e607fcd59d3c177ac47cf2dc.

**Comment by davidhedlund** [comment]
> No error. See [14aefcd](https://github.com/dsalt/devilspie2/commit/14aefcdbf9f94074e607fcd59d3c177ac47cf2dc).

Oh.

Then
```
  -- 'millisleep' is new to 0.46. The 0.1s delay for older versions:
  --   option 1:
  --     os.execute("sleep 0.1")
```

should be replaced with:
```
  -- 'maximise', and 'millisleep', is new to 0.46. The 0.1s delay for older versions:
  --   option 1:
  --     os.execute("sleep 0.1")
  --     maximize()
```

**Comment by dsalt** [comment]
I'm keeing `maximise()`, but with added comments; see 536d854f86b4656ab081dcd79ba0e7472d46ec01.

**Comment by davidhedlund** [comment]
> I'm keeping `maximise()`, but with added comments; see [536d854](https://github.com/dsalt/devilspie2/commit/536d854f86b4656ab081dcd79ba0e7472d46ec01).

Thank you again.

**Comment by davidhedlund** [comment]
I wanted to take a moment to express my sincere gratitude for all the time and effort you've dedicated to helping us. I appreciate the patience and enthusiasm you've shown throughout the process.

**Pull request merged**
